name: Create the DEB

on:
  workflow_dispatch:

jobs:
  Create_Packages:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Configure GPG Key
       run: |
         echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
       env:
         GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Install package
        run: |
        sudo apt-get install dpkg-dev devscripts
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Build pacakge
        run: |
          cd repo/contrib/hello
          debuild -S
