name: Create the DEB
on:
  workflow_dispatch:
jobs:
  Create_Packages:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | gpg --import --batch
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Add the custom signing program
        run: |
          cat > /tmp/sign.sh << EOF
          #!/bin/bash
          echo "Start the signing process..."
          echo \$@
          gpg --batch --pinentry-mode=loopback --passphrase "$GPG_KEY_PASSPHRASE" \$@
          EOF
          chmod +x /tmp/sign.sh
        env:
          GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
      - name: Install packages
        run: |
          sudo apt-get install dpkg-dev devscripts debhelper
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Build pacakge
        run: |
          cd repo/contrib/hello
          dpkg-buildpackage -S --sign-key="$GPG_KEY_ID" --sign-command=/tmp/sign.sh
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      - name: Upload to PPA
        run: |
          dput ppa:dirksu/test repo/contrib/*.changes
